# Generated by Django 3.2.8 on 2022-05-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordHtml',
            new_name='PlagiarismRecordU_2',
        ),
    ]
