# Generated by Django 4.0.4 on 2022-05-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_id', models.CharField(max_length=15)),
                ('unit', models.IntegerField()),
                ('sprint', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_1', models.CharField(max_length=15)),
                ('student_2', models.CharField(max_length=15)),
                ('similarity_coeff', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.report')),
            ],
        ),
    ]
