# Generated by Django 3.2.8 on 2022-05-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_recordhtml_plagiarismrecordu_2'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='PlagiarismRecordU_3',
        ),
        migrations.RenameModel(
            old_name='Report',
            new_name='PlagiarismReport',
        ),
    ]
